# Generated by Django 5.0.3 on 2024-04-02 18:08

import account.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('country', models.CharField(choices=[('Australia', '澳大利亚'), ('Belarus', '白俄罗斯'), ('Belgium', '比利时'), ('Brazil', '巴西'), ('Canada', '加拿大'), ('Chile', '智利'), ('China', '中国'), ('Estonia', '爱沙尼亚'), ('Finland', '芬兰'), ('France', '法国'), ('Germany', '德国'), ('Greece', '希腊'), ('Guatemala', '危地马拉'), ('Haiti', '海地'), ('Hungary', '匈牙利'), ('Iceland', '冰岛'), ('India', '印度'), ('Ireland', '爱尔兰'), ('Italy', '意大利'), ('Japan', '日本'), ('Mexico', '墨西哥'), ('Montenegro', '黑山'), ('Netherlands', '荷兰'), ('Norway', '挪威'), ('Peru', '秘鲁'), ('Russia', '俄罗斯'), ('South Korea', '韩国'), ('Spain', '西班牙'), ('Sweden', '瑞典'), ('Switzerland', '瑞士'), ('United Kingdom', '英国'), ('United States', '美国')], max_length=50, verbose_name='国家')),
                ('city', models.CharField(max_length=50, verbose_name='市区')),
                ('street', models.CharField(max_length=100, verbose_name='街道')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('zip_code', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('phone', models.CharField(max_length=20, verbose_name='手机')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='小计')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总计')),
                ('payment_type', models.PositiveSmallIntegerField(choices=[(0, '在线支付'), (1, '信用卡/储蓄卡'), (2, '货到付款'), (3, '其他')], default=0, verbose_name='支付方式')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '准备配送'), (1, '配送中'), (2, '已完成'), (3, '已取消')], default=0, verbose_name='订单状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='下单日期')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'wishlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='用户名')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='头像')),
                ('is_active', models.BooleanField(default=False, verbose_name='已激活')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级用户')),
                ('is_staff', models.BooleanField(default=False, verbose_name='员工')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册日期')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最近一次登录')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '账号',
                'verbose_name_plural': '账号',
                'db_table': 'user',
            },
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('country', models.CharField(choices=[('Australia', '澳大利亚'), ('Belarus', '白俄罗斯'), ('Belgium', '比利时'), ('Brazil', '巴西'), ('Canada', '加拿大'), ('Chile', '智利'), ('China', '中国'), ('Estonia', '爱沙尼亚'), ('Finland', '芬兰'), ('France', '法国'), ('Germany', '德国'), ('Greece', '希腊'), ('Guatemala', '危地马拉'), ('Haiti', '海地'), ('Hungary', '匈牙利'), ('Iceland', '冰岛'), ('India', '印度'), ('Ireland', '爱尔兰'), ('Italy', '意大利'), ('Japan', '日本'), ('Mexico', '墨西哥'), ('Montenegro', '黑山'), ('Netherlands', '荷兰'), ('Norway', '挪威'), ('Peru', '秘鲁'), ('Russia', '俄罗斯'), ('South Korea', '韩国'), ('Spain', '西班牙'), ('Sweden', '瑞典'), ('Switzerland', '瑞士'), ('United Kingdom', '英国'), ('United States', '美国')], max_length=50, verbose_name='国家')),
                ('city', models.CharField(max_length=50, verbose_name='市区')),
                ('street', models.CharField(max_length=100, verbose_name='街道')),
                ('province', models.CharField(max_length=50, verbose_name='省')),
                ('zip_code', models.CharField(max_length=20, verbose_name='邮政编码')),
                ('phone', models.CharField(max_length=20, verbose_name='手机')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'db_table': 'address',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
                'db_table': 'cart',
                'ordering': ['-created_at'],
            },
        ),
    ]
