# Generated by Django 5.0.3 on 2024-04-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattachment',
            options={'ordering': ('-order',), 'verbose_name': '商品附件', 'verbose_name_plural': '商品附件'},
        ),
        migrations.AddField(
            model_name='productattachment',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='product.product'),
        ),
    ]
