# Generated by Django 5.0.3 on 2024-04-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='productattachment',
            options={'ordering': ('order',), 'verbose_name': '商品附件', 'verbose_name_plural': '商品附件'},
        ),
    ]
